apiVersion: apps/v1
kind: Deployment
metadata:
  name: springtest
spec:
  selector:
    matchLabels:
      app: springtest
  replicas: 1
  template:
    metadata:
      labels:
        app: springtest
    spec:
      containers:
        - name: springtest
          image: cipyout31/springtest:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: springtest
spec:
  selector:
    app: springtest
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
      nodePort: 30001
  type: NodePort